# Config file for creating container
# https://github.com/SU-SWS/drupal-caravan
# ========================================
#
server:                            "sites2"
container_name:                    "drupalvm"
container_distro:                  "ubuntu1604"
container_ip_address:              "192.168.88.88"
localhost_http_port:               9000
localhost_https_port:              9001
container_webserver_root:          "/var/www/"
localhost_ssh_port:                "2020"

mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

apache_vhosts:
  - servername: "{{ drupal_domain }}.local"
    serveralias: "www.{{ drupal_domain }}.local"
    documentroot: "/var/www/{{ drupal_domain }}"
    extra_parameters: |
      <FilesMatch \.php$>
        SetHandler "proxy:fcgi://127.0.0.1:9000"
      </FilesMatch>

  - servername: "behat.{{ drupal_domain }}.local"
    documentroot: "/var/www/{{ drupal_domain }}/reports/behat"
